apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: k8s-demo
spec:
  selector:
    matchLabels:
      app: hello-app
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app-svc
        image: "larryso/sample-hello-app:2.0"