apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: k8s-demo
  labels:
    run: my-nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
