apiVersion: v1
kind: Service
metadata:
  namespace: tests
  name: hello-service-nodeport
spec:
  type: NodePort
  selector:
    app: hello
  ports:
  - nodePort: 30163
    port: 8081
    targetPort: 8080
